### ISSUE TITLE
ITK / numpy errors on master

### ISSUE THREAD

**Issue by finetjul** [KitwareMedical/paraview-glance-py#25]
With itk 5.2, I got the following errors:
```
python server.py --port 8181 --no-browser
Traceback (most recent call last):
  File "server.py", line 11, in <module>
    from hello_world import AlgorithmApi
  File "C:\Work\ParaViewGlance\paraview-glance-py\server\hello_world.py", line 2, in <module>
    import itk
  File "C:\Work\ParaViewGlance\paraview-glance-py\env\lib\site-packages\itk\__init__.py", line 28, in <module>
    from itk.support.extras import *
  File "C:\Work\ParaViewGlance\paraview-glance-py\env\lib\site-packages\itk\support\extras.py", line 25, in <module>
    from numpy.typing import ArrayLike
  File "C:\Work\ParaViewGlance\paraview-glance-py\env\lib\site-packages\numpy\typing\__init__.py", line 315, in <module>
    from ._shape import _Shape, _ShapeLike
  File "C:\Work\ParaViewGlance\paraview-glance-py\env\lib\site-packages\numpy\typing\_shape.py", line 15, in <module>
    _ShapeLike = Union[SupportsIndex, Sequence[SupportsIndex]]
  File "C:\work\Python\Python374\lib\typing.py", line 254, in inner
    return func(*args, **kwds)
  File "C:\work\Python\Python374\lib\typing.py", line 629, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\work\Python\Python374\lib\typing.py", line 629, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\work\Python\Python374\lib\typing.py", line 142, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got NotImplemented.
```

**Comment by finetjul** [comment]
Actually, it is due to the dependency of itk 5.03b that installs itk modules >= 5.03 (and in this case 5.2 which seems to be the issue).

Upgrading to itk 5.1.0 fixes the error
